pipeline {

environment {

    AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    DOCKER_PASSWD = credentials('DOCKER_PASSWD')
}

    agent { node { label 'agent1' } }

    stages {
        stage('Cloning Git') {
            steps {
                git branch: 'main', credentialsId: 'jenkins_master_git', url: 'git@github.com:anna-shcherbak/flask-blog-01.git'
            }
        }
        
        stage("Build images") {
	    steps {
              sh 'docker login -uannetta -p $DOCKER_PASSWD'
	      sh "docker-compose build"
              sh "docker-compose push" 

               }
        }
        
        stage("Run app") {
	    steps {
                  sshagent(['jenkins_master']){
                  sh "ssh -o StrictHostKeyChecking=no ec2-user@3.68.68.21 \"cd /home/ec2-user/flask_app ; docker-compose pull; docker-compose stop ; docker-compose up -d \" "
                  }

               }
        }




    }
    post {
        always  {
            deleteDir()
        }
    }

}
